### ISSUE TITLE
[TEAM A] [PRESENTATION] Milestone 2 Slides

### ISSUE THREAD

**Issue by b2af** [umgc/Summer2024#198]
- [ ] TDD Design Overview @lariasse 
- [x] TDD Architectural Design​ @shall129

**Comment by b2af** [comment]
- [ ] TDD Design Overview
- [ ]
